# Site
title:              "Kudlac's"
logo:               "Giraffe"
bio:                "Kudlac's - osobní stránky"
description:        "Kudlac's - osobní stránky"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
previous: 'http://kudlac.tode.cz/second/'

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         assets/sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
facebook:           vladan.kudlac
instagram:          kudlav
github:             kudlav

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
