title: "Kudlac's"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
permalink: '/:title/'
collections:
  posts:
    permalink: '/myown/:title/'
description: "Kudlac's - osobní stránky"
header:
  title: Kudlac's
  tagline: osobní stránky
  logo_img: assets/images/logo.webp
  background_img: assets/images/bg.webp
  has_nav: true
  nav_links:
    - label: Úvod
      url: /
      style: link
    - label: Tvorba
      url: /myown/
      style: link
    - label: Co mám rád
      url: /like/
      style: link
    - label: Cíle
      url: /goals/
      style: link
  has_social: true
  social_links:
    - label: Facebook
      url: 'https://facebook.com/vladan.kudlac'
      style: icon
      icon_class: fa-facebook
      new_window: true
    - label: Instagram
      url: 'https://instagram.com/kudlav'
      style: icon
      icon_class: fa-instagram
      new_window: true
    - label: GitHub
      url: 'https://github.com/kudlav'
      style: icon
      icon_class: fa-github
      new_window: true
    - label: Předchozí verze
      url: 'http://kudlac.tode.cz/second/'
      new_window: true
palette: yellow
sass:
  indentWidth: 4
  style: nested
  precision: 10
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
