# Site
title:              "Kudlac's"
logo:               "Giraffe"
bio:                "Kudlac's - osobní stránky"
description:        "Kudlac's - osobní stránky"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
previous: 'http://kudlac.tode.cz/second/'

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/myown/:title/"
    layout: post
    author:

# Jekyll
permalink:          /myown/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         assets/sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
facebook:           vladan.kudlac
instagram:          kudlav
github:             kudlav

# Plugins
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
#  - jekyll-paginate

#paginate: 6
#paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# default excludes
exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
